# Generated by Django 2.2 on 2020-12-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Entry recorded prior to this row being added. Please edit in any notes!'),
            preserve_default=False,
        ),
    ]
